trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dontnet build --configuration $(buildconfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
